#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Hook to prevent pushing to master branch
BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCH="master"

if [ "$BRANCH" = "$PROTECTED_BRANCH" ]; then
  echo "Direct push to $PROTECTED_BRANCH branch is not allowed."
  echo "Please create a pull request instead."
  exit 1
fi